package image.bean;

import java.util.Date;

public class PictureDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column picture.id
     *
     * @mbg.generated Fri Jul 05 14:21:25 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column picture.path
     *
     * @mbg.generated Fri Jul 05 14:21:25 CST 2019
     */
    private String path;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column picture.url
     *
     * @mbg.generated Fri Jul 05 14:21:25 CST 2019
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column picture.hash
     *
     * @mbg.generated Fri Jul 05 14:21:25 CST 2019
     */
    private String hash;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column picture.md5
     *
     * @mbg.generated Fri Jul 05 14:21:25 CST 2019
     */
    private String md5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column picture.category
     *
     * @mbg.generated Fri Jul 05 14:21:25 CST 2019
     */
    private Integer category;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column picture.keywords
     *
     * @mbg.generated Fri Jul 05 14:21:25 CST 2019
     */
    private String keywords;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column picture.create_time
     *
     * @mbg.generated Fri Jul 05 14:21:25 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column picture.update_time
     *
     * @mbg.generated Fri Jul 05 14:21:25 CST 2019
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column picture.delete_time
     *
     * @mbg.generated Fri Jul 05 14:21:25 CST 2019
     */
    private Integer deleteTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column picture.id
     *
     * @return the value of picture.id
     *
     * @mbg.generated Fri Jul 05 14:21:25 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column picture.id
     *
     * @param id the value for picture.id
     *
     * @mbg.generated Fri Jul 05 14:21:25 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column picture.path
     *
     * @return the value of picture.path
     *
     * @mbg.generated Fri Jul 05 14:21:25 CST 2019
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column picture.path
     *
     * @param path the value for picture.path
     *
     * @mbg.generated Fri Jul 05 14:21:25 CST 2019
     */
    public void setPath(String path) {
        this.path = path == null ? null : path.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column picture.url
     *
     * @return the value of picture.url
     *
     * @mbg.generated Fri Jul 05 14:21:25 CST 2019
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column picture.url
     *
     * @param url the value for picture.url
     *
     * @mbg.generated Fri Jul 05 14:21:25 CST 2019
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column picture.hash
     *
     * @return the value of picture.hash
     *
     * @mbg.generated Fri Jul 05 14:21:25 CST 2019
     */
    public String getHash() {
        return hash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column picture.hash
     *
     * @param hash the value for picture.hash
     *
     * @mbg.generated Fri Jul 05 14:21:25 CST 2019
     */
    public void setHash(String hash) {
        this.hash = hash == null ? null : hash.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column picture.md5
     *
     * @return the value of picture.md5
     *
     * @mbg.generated Fri Jul 05 14:21:25 CST 2019
     */
    public String getMd5() {
        return md5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column picture.md5
     *
     * @param md5 the value for picture.md5
     *
     * @mbg.generated Fri Jul 05 14:21:25 CST 2019
     */
    public void setMd5(String md5) {
        this.md5 = md5 == null ? null : md5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column picture.category
     *
     * @return the value of picture.category
     *
     * @mbg.generated Fri Jul 05 14:21:25 CST 2019
     */
    public Integer getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column picture.category
     *
     * @param category the value for picture.category
     *
     * @mbg.generated Fri Jul 05 14:21:25 CST 2019
     */
    public void setCategory(Integer category) {
        this.category = category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column picture.keywords
     *
     * @return the value of picture.keywords
     *
     * @mbg.generated Fri Jul 05 14:21:25 CST 2019
     */
    public String getKeywords() {
        return keywords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column picture.keywords
     *
     * @param keywords the value for picture.keywords
     *
     * @mbg.generated Fri Jul 05 14:21:25 CST 2019
     */
    public void setKeywords(String keywords) {
        this.keywords = keywords == null ? null : keywords.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column picture.create_time
     *
     * @return the value of picture.create_time
     *
     * @mbg.generated Fri Jul 05 14:21:25 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column picture.create_time
     *
     * @param createTime the value for picture.create_time
     *
     * @mbg.generated Fri Jul 05 14:21:25 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column picture.update_time
     *
     * @return the value of picture.update_time
     *
     * @mbg.generated Fri Jul 05 14:21:25 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column picture.update_time
     *
     * @param updateTime the value for picture.update_time
     *
     * @mbg.generated Fri Jul 05 14:21:25 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column picture.delete_time
     *
     * @return the value of picture.delete_time
     *
     * @mbg.generated Fri Jul 05 14:21:25 CST 2019
     */
    public Integer getDeleteTime() {
        return deleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column picture.delete_time
     *
     * @param deleteTime the value for picture.delete_time
     *
     * @mbg.generated Fri Jul 05 14:21:25 CST 2019
     */
    public void setDeleteTime(Integer deleteTime) {
        this.deleteTime = deleteTime;
    }
}