package cn.jp.dao;

import cn.jp.bean.UserMoreDO;
import org.springframework.stereotype.Service;

@Service
public interface UserMoreDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_more
     *
     * @mbg.generated Mon Dec 02 15:55:52 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_more
     *
     * @mbg.generated Mon Dec 02 15:55:52 CST 2019
     */
    int insert(UserMoreDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_more
     *
     * @mbg.generated Mon Dec 02 15:55:52 CST 2019
     */
    int insertSelective(UserMoreDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_more
     *
     * @mbg.generated Mon Dec 02 15:55:52 CST 2019
     */
    UserMoreDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_more
     *
     * @mbg.generated Mon Dec 02 15:55:52 CST 2019
     */
    int updateByPrimaryKeySelective(UserMoreDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_more
     *
     * @mbg.generated Mon Dec 02 15:55:52 CST 2019
     */
    int updateByPrimaryKey(UserMoreDO record);
}