package cn.jp.bean;

import org.springframework.stereotype.Repository;

import java.util.Date;

@Repository
public class UserMoreDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_more.id
     *
     * @mbg.generated Mon Dec 02 15:55:52 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_more.user_id
     *
     * @mbg.generated Mon Dec 02 15:55:52 CST 2019
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_more.token
     *
     * @mbg.generated Mon Dec 02 15:55:52 CST 2019
     */
    private String token;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_more.sc_type
     *
     * @mbg.generated Mon Dec 02 15:55:52 CST 2019
     */
    private Integer scType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_more.create_time
     *
     * @mbg.generated Mon Dec 02 15:55:52 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_more.update_time
     *
     * @mbg.generated Mon Dec 02 15:55:52 CST 2019
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_more.delete_time
     *
     * @mbg.generated Mon Dec 02 15:55:52 CST 2019
     */
    private Integer deleteTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_more.id
     *
     * @return the value of user_more.id
     *
     * @mbg.generated Mon Dec 02 15:55:52 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_more.id
     *
     * @param id the value for user_more.id
     *
     * @mbg.generated Mon Dec 02 15:55:52 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_more.user_id
     *
     * @return the value of user_more.user_id
     *
     * @mbg.generated Mon Dec 02 15:55:52 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_more.user_id
     *
     * @param userId the value for user_more.user_id
     *
     * @mbg.generated Mon Dec 02 15:55:52 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_more.token
     *
     * @return the value of user_more.token
     *
     * @mbg.generated Mon Dec 02 15:55:52 CST 2019
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_more.token
     *
     * @param token the value for user_more.token
     *
     * @mbg.generated Mon Dec 02 15:55:52 CST 2019
     */
    public void setToken(String token) {
        this.token = token == null ? null : token.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_more.sc_type
     *
     * @return the value of user_more.sc_type
     *
     * @mbg.generated Mon Dec 02 15:55:52 CST 2019
     */
    public Integer getScType() {
        return scType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_more.sc_type
     *
     * @param scType the value for user_more.sc_type
     *
     * @mbg.generated Mon Dec 02 15:55:52 CST 2019
     */
    public void setScType(Integer scType) {
        this.scType = scType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_more.create_time
     *
     * @return the value of user_more.create_time
     *
     * @mbg.generated Mon Dec 02 15:55:52 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_more.create_time
     *
     * @param createTime the value for user_more.create_time
     *
     * @mbg.generated Mon Dec 02 15:55:52 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_more.update_time
     *
     * @return the value of user_more.update_time
     *
     * @mbg.generated Mon Dec 02 15:55:52 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_more.update_time
     *
     * @param updateTime the value for user_more.update_time
     *
     * @mbg.generated Mon Dec 02 15:55:52 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_more.delete_time
     *
     * @return the value of user_more.delete_time
     *
     * @mbg.generated Mon Dec 02 15:55:52 CST 2019
     */
    public Integer getDeleteTime() {
        return deleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_more.delete_time
     *
     * @param deleteTime the value for user_more.delete_time
     *
     * @mbg.generated Mon Dec 02 15:55:52 CST 2019
     */
    public void setDeleteTime(Integer deleteTime) {
        this.deleteTime = deleteTime;
    }
}